2023-07-29 22:26:03.180 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-29 22:26:03.180 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration snooz which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-29 22:26:03.180 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration dreo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-29 22:26:06.275 ERROR (MainThread) [custom_components.hacs] HACS is disabled - invalid_token
2023-07-29 22:26:06.280 ERROR (MainThread) [custom_components.hacs] Bad credentials
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 464, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/base.py", line 522, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Bad credentials
2023-07-29 22:51:09.164 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x50'
2023-07-29 23:47:04.210 WARNING (MainThread) [pyatv.support.http] Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'Date': 'Sun, 30 Jul 2023 06:46:56 GMT', 'Content-Length': '55', 'Content-Type': 'application/x-apple-binary-plist', 'Server': 'AirTunes/695.5.1', 'CSeq': '2400'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')
2023-07-29 23:47:08.217 WARNING (MainThread) [homeassistant.components.apple_tv] Connection lost to Apple TV "Living Room"
2023-07-30 00:04:04.975 WARNING (MainThread) [pyatv.support.http] Got response without having a request: HttpResponse(protocol='RTSP', version='1.0', code=200, message='OK', headers={'Date': 'Sun, 30 Jul 2023 07:04:04 GMT', 'Content-Length': '55', 'Content-Type': 'application/x-apple-binary-plist', 'Server': 'AirTunes/695.5.1', 'CSeq': '2819'}, body=b'bplist00\xd1\x01\x02Wstreams\xa0\x08\x0b\x13\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14')
2023-07-30 00:04:08.978 WARNING (MainThread) [homeassistant.components.apple_tv] Connection lost to Apple TV "Bedroom"
2023-07-30 00:17:35.150 WARNING (MainThread) [homeassistant.components.apple_tv] Connection lost to Apple TV "Bedroom"
2023-07-30 00:34:32.481 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2023-07-30 01:44:18.494 WARNING (Thread-3 (_thread_main)) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2023-07-30 01:44:18.504 WARNING (Thread-3 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.0.212, code UNKNOWN_ERROR
2023-07-30 01:44:18.506 WARNING (Thread-3 (_thread_main)) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2023-07-30 01:44:18.507 WARNING (Thread-3 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.0.212, code UNKNOWN_ERROR
2023-07-30 02:26:14.309 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0xc4'
2023-07-30 06:26:18.591 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x36'
2023-07-30 07:10:28.223 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.20 data: Unable to connect to the device: 192.168.0.20: 
2023-07-30 07:10:30.132 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.237 data: Unable to connect to the device: 192.168.0.237: 
2023-07-30 07:10:30.260 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.200 data: Unable to connect to the device: 192.168.0.200: 
2023-07-30 07:10:30.386 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.177 data: Unable to connect to the device: 192.168.0.177: 
2023-07-30 07:10:30.388 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.112 data: Unable to connect to the device: 192.168.0.112: 
2023-07-30 07:10:30.398 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.87 data: Unable to connect to the device: 192.168.0.87: 
2023-07-30 07:10:30.414 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.110 data: Unable to connect to the device: 192.168.0.110: 
2023-07-30 07:10:30.433 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.98 data: Unable to connect to the device: 192.168.0.98: 
2023-07-30 07:10:30.455 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.8 data: Unable to connect to the device: 192.168.0.8: 
2023-07-30 07:10:31.397 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.88 data: Unable to connect to the device: 192.168.0.88: 
2023-07-30 07:11:31.440 WARNING (Thread-4 (_thread_main)) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2023-07-30 07:11:31.441 WARNING (Thread-4 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.0.114, code UNKNOWN_ERROR
2023-07-30 07:11:31.442 WARNING (Thread-4 (_thread_main)) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2023-07-30 07:11:31.443 WARNING (Thread-4 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.0.114, code UNKNOWN_ERROR
2023-07-30 10:26:22.857 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0xb3'
